### ISSUE TITLE
Naming of your files. 

### ISSUE THREAD

**Issue by Raziel7893** [Kickbut101/WindowsGSM.DontStarveTogether#1]
Your Plugin can't be installed correctly with the Download Code and then import Plugin Button, as your filenames don't match the Project name.  
When you import the code zip file, the plugin gets dumped in a Folder named DontStarveTogether, while the files inside are still named DST.cs, which WindowsGSM can't handle.  (and does not make sense to be honest, as the Import itself is successful, but WindowsGSM does not list it in the GameList, i gues due to the name missmatch from folder and codefile) 

I would suggest renaming the files and folder from the shortened Name to the one inside your ProjectName.  (DST.cs =>DontStarveTogether.cs )

Issue: 
https://discord.com/channels/590590698907107340/748167735661428806/1214066954894053436

**Comment by Kickbut101** [comment]
This plugin is like 3 years old. I'm surprised it worked for this long. You'll probably want to fork this and fix it. I haven't touched windowsGSM in at least 2 years.
